spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/traffic?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
